language: php

php:
  - 5.4
  - 5.5
  - hhvm

before_script:
  - mkdir -p build/logs
  - curl -s http://getcomposer.org/installer | php
  - php composer.phar require --dev satooshi/php-coveralls:dev-master
  - php composer.phar install --dev --no-interaction

script:
  - sh -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then ./vendor/bin/phpcs --standard=phpcs.xml ./src/; fi;'
  - sh -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then ./vendor/bin/phpcs --standard=phpcs.xml ./tests/; fi;'
  - sh -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then ./vendor/bin/phpmd ./src/ text phpmd.xml; fi;'
  - sh -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then ./vendor/bin/phpmd ./tests/ text phpmd.xml; fi;'
  - sh -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then ./vendor/bin/parallel-lint ./src/; fi;'
  - sh -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then ./vendor/bin/parallel-lint ./tests/; fi;'
  - ./vendor/bin/phpunit --coverage-clover build/logs/clover.xml

after_script:
  - php vendor/bin/coveralls -v

matrix:
  allow_failures:
    - php: hhvm
  fast_finish: true